### ISSUE TITLE
swagger intergration

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#108]
REF: https://towardsdatascience.com/working-with-apis-using-flask-flask-restplus-and-swagger-ui-7cf447deda7f

**Comment by ManZzup** [comment]
Swagger added

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] full task

**Comment by MrClemRkz** [comment]
@ManZzup this is complete right?

**Comment by MrClemRkz** [comment]
this is complete.
