### ISSUE TITLE
Auto escalate review on Incident to upper level roles

### ISSUE THREAD

**Issue by ManZzup** [ECLK/IncidentManagement#113]
Auto escalation takes place within the EC users
- upon default set time duration is passed, incident should be auto escalated upper level for attention and action. 
- this should be logged on the event trail.

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] role hierarchy maintenance (b)
- [ ] business logic and implementation on auto assignment (b)

**Comment by ManZzup** [comment]
Auto escalate done

**Comment by ManZzup** [comment]
Need to fix a crob job to automate
