### ISSUE TITLE
Incident Workflows 

### ISSUE THREAD

**Issue by ManZzup** [ECLK/IncidentManagement#117]
Following workflows are discussed and are implemented as UI actions in the system

# 1). Verify incident

1. Complain coordinator clicks "Verify" button
2. Dialog opens and set comment
3. Incident status change -> Verified
4. Incident escalated

# 2) Escalate incident

1.  Anyone clicks "Escalate" button
2.  Incident assignee changed to new user higher in the hierarchy

# 3) Request action to incident (Escalate external)

1. Manager clicks "Take action" button
2. Dialog opens and set Entitty, Name, Contact, Reason
3. Incident status change to "Action pending"

# 4) Provide action to requested action

1. Manager click "Resolve action" button
2. Dialog open and set Comment and check if it's an out come or not
3. Incident status change to "Action taken"

# 5) Request advise for incident

1. Coordinator / Manager click "Request advice"
2. Dialog open and set Comment and Assgnee to direct the query
3. Incident status change to "Advice requested"
4. Assignee added as a Linked Individual

# 6) Provide advice for requested incident

1. Manager or above recieves request for advice
2. Clicks on "Advice" button
3. Dialog opens and set advice comment and submit
4. Incident status change to "Advice provided"
5. Assignee removed from linked individuals

# 7) Close incident

1. Manager or above clicks on Close
2. Dialog opens and set comment 
3. Status change to "Closed"

# 8) Change incident assignee

1. Manager or above change the assingee
2. Incident assignee changes

**Comment by ManZzup** [comment]
- [ ] Verify incident
- [ ] Escalate incident
- [ ] Request action to incident (Escalate external)
- [ ] Provide action to requested action
- [ ] Request advise for incident
- [ ] Provide advice for requested incident
- [ ] Close incident
- [ ] Change incident assignee

**Comment by ManZzup** [comment]
## Workflow Backend API

**POST** `/incident/<incident_id>/workflow/<workflow_type>`

### workflow_type 
verify
escalate
request-action
complete-action
request-advice
provide-advice
close
assign

### Request body
```javascript
{
    "comment": [Object custom-comment-object],
    "assignee": assignee-id,
    "start_event": start event id for action taken workflow
}
```

**Comment by lahiru94** [comment]
Workflow functionality is done with basic UIs.
