### ISSUE TITLE
[Refactor] Rearrange redux actions in Incident Filing

### ISSUE THREAD

**Issue by lahiru94** [ECLK/IncidentManagement#120]
Decouple Incident Update and Stepper advance actions.

**Comment by MrClemRkz** [comment]
## task breakdown
(need support here) @lahiru94

**Comment by lahiru94** [comment]
some of the redux actions related to Incident CRUD are coupled with other UI actions (eg: Crate Incident action also advance stepper flag.)  
Those need to be decoupled. CRUD actions should not have any other functionality within them.
