### ISSUE TITLE
UI Component - Slider with steps

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#138]
dependency: #228 
- steps are to be numbers
- steps must be passed by a prop to the component

**Comment by Kirishikesan** [comment]
import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import Slider from '@material-ui/core/Slider';



export default class MySlider extends React.Component{
  constructor(props) {
    super(props);
        this.state = {
      position:"0",
      marks:[
        {
          value: 0,
          label: '0',
        },
        {
          value: 10,
          label: '10',
        },
        {
          value: 20,
          label: '20',
        },
        {
          value: 30,
          label: '30',
        },
        {
          value: 40,
          label: '40',
        },
        {
          value: 50,
          label: '50',
        },
        {
          value: 60,
          label: '60',
        },
        {
          value: 70,
          label: '70',
        },
        {
          value: 80,
          label: '90',
        },
        {
          value: 90,
          label: '90',
        },
        {
          value: 100,
          label: '100',
        },
      ]
    } ;
  }
  
handleChange=()=>{
  this.setState({position:this.Slider.value});
}

render() {
    return (      
      <div>
      <Typography id="Slider with steps" gutterBottom>
        Values
      </Typography>
      <Slider onDragLeave = {this.handleChange()}

        defaultValue={30} 
        getAriaValueText={this.value}
        aria-labelledby="discrete-slider"
        valueLabelDisplay="auto"
        step={10}
        marks={this.state.marks}
        min={0}
        max={100}
      />
    </div>
  );    
}}
