### ISSUE TITLE
Seperate styls/css from react code

### ISSUE THREAD

**Issue by kanchw** [ECLK/IncidentManagement#145]
I noticed few suggestion when I glanced at the code : These are medium/ minor code structuring issues , still if fixed it will bring more readable/produce reusable CSS and maintainable code . In general UI code should be more simplify as react code provides that luxury than angular/js dose .

here are my comments
 example:
frontend/src/modules/incident-filing/components/IncidentForm.js

Across front-end components styling/css code is mixed with react code, that drives a large code base, less readability and hard to maintain code base, These css, styling can be isolated in a cssfile.css and import in react code.Also by identifying reusble styleing/css across components such as tables,buttons, forms , colors etc you may produce a single css file to use for all components (Please share a mock screen if you have). 
If  that is the case, reusable .css file's physical location   can be stayed in a static folder but this location should be chosen according to deployment architecture (which i don't right now) if you are trying to go as micro services.
`

example code : please notice app.js has imported .css file in the component level 

Improving naming conventions 
-----------------------------------
folder/react files naming conventions ideally follow business use /use case such as 
IncidentManagement/frontend

rather preferably can be called IncidentManagement/IncidentManagementUI 

For example such as Landing page / it dose not carry a business sense when which to which it gets landed , I would think to improve naming conversions.

Internationalization is compromised 
-----------------------------------------

In the same file there are hard coded error messages/validations information messages are in English. That will compromise the i18n

Form validation/error handling can me moved to different individual react files and use error key value pair for validation and error handling.
are there suppose to be axio calls a,d server side validations too?

**Comment by MrClemRkz** [comment]
this is neglected, thus will be closed.
