### ISSUE TITLE
Pls consider Accessibility (ADA) in html elements 

### ISSUE THREAD

**Issue by kanchai123** [ECLK/IncidentManagement#146]
ADA is an import feature specially building a software for public, should maintain equal opportunities. It’s well understood that the initial phase of the project  is just a working software . But if the developer can go extra mile use accessibly compliance react html elements to use as a best practice , in the future rework/conversion effort would be very less . As far as incident form is not even closer to ADA , please read the following docs which provides more insight about react accessibility compliance referances/example if the developer can use those as  best practice then and there as much can would be beneficial rather working as a conversion effort later . Will share more detail about accessibility . A champion developer may start contributing and keep an eye on coding for this . 

https://reactjs.org/docs/accessibility.html

**Comment by MrClemRkz** [comment]
this is neglected, thus will be closed.
