### ISSUE TITLE
uploaded file cannot view or download from event trail

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#158]

**Comment by ManZzup** [comment]
@MrClemRkz clarification needed
file upload works as expected,
1. select / drop file to upload zone
2. press "Upload" button

ref:

![Selection_198](https://user-images.githubusercontent.com/3193991/64474889-b5646300-d198-11e9-9ed5-db7e4fa467b5.png)

**Comment by ManZzup** [comment]
Resolved.
