### ISSUE TITLE
New incident life cycle options

### ISSUE THREAD

**Issue by ManZzup** [ECLK/IncidentManagement#172]
**Is your feature request related to a problem? Please describe.**
Incident has no way of showing invalid incidents (bogus).
Valid incidents again should be
1. With proof
2. Without proof

**Describe the solution you'd like**
1. Provide an additional status to say "invalid" and additional workflow to invalidate
2. Provide an option to mark a verification with or without proof

**Describe alternatives you've considered**
None

**Additional context**

**Comment by aijdissanayake** [comment]
Added new Status Type - Invalidated and new workflow created
Added Proof Boolean field to the Incident table
