### ISSUE TITLE
Issues in the public user incident create form

### ISSUE THREAD

**Issue by ManZzup** [ECLK/IncidentManagement#174]
**Describe the bug**
Following minor UI fixes are there
- [x] Change to 'Describe the location'
- [x] "In the Your contact details section, change the message to
Optional - you may submit your complaint anonymously. If you choose to do so, you will not be able to obtain status updates from the Election Commission of Sri Lanka"
- [x] Include a line for Mobile phone number and Land line 
- [x] Message to the user - "Your complaint has been submitted successfully". Upon submission of the complaint, the user is directed to a plain screen page with this message. This page also has a button which allows the user to create another complaint, add/ edit information to the submitted complaint or check the status of the submitted complaint. 
- [x] After the complaint has been submitted you cannot see the reset button.
- [x] At the top of the screen, the button reads GO BACK. It should read BACK

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by lahiru94** [comment]
@ManZzup Add additional fields to store landline and mobile number separately in reporter table.

**Comment by ManZzup** [comment]
@lahiru94  field added
reporter.telephone -> landline contact
reporter.mobile -> mobile contact

**Comment by MrClemRkz** [comment]
relates #252

**Comment by MrClemRkz** [comment]
![Screen Shot 2019-10-17 at 1 40 22 PM](https://user-images.githubusercontent.com/16492984/66991340-7ef9fc00-f0e5-11e9-88d2-bba4d6727476.png)

**Comment by MrClemRkz** [comment]
completed.
