### ISSUE TITLE
change 'severity' on review page

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#180]
**Is your feature request related to a problem? Please describe.**
Cannot update severity once set.

**Describe the solution you'd like**
Set severity update from review page on a modal.

**Describe alternatives you've considered**
review change on edit page. set review on create page. review value is set on incident table

**Additional context**
none

**Comment by MrClemRkz** [comment]
- [ ] add severity on 'create incident form'
- [ ] edit severity on 'create incident form'
- [ ] show severity on 'review indent view'

**Comment by ManZzup** [comment]
This is fixed
