### ISSUE TITLE
police data insert on 'create incident' view

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#182]
**Is your feature request related to a problem? Please describe.**
police views

**Describe the solution you'd like**
insert police data - create incident view, can be shown in expanding way.
view police data - review incident view

**Describe alternatives you've considered**
none.

**Additional context**
- police users will be using it specifically
- new tab can be added as 'police data' to the review page.

**Comment by lahiru94** [comment]
@MrClemRkz is this an extension to the existing internal create incident form or do we need to provide a separate view for the police users and keep the existing internal create incident form as it is.

**Comment by MrClemRkz** [comment]
it is a extension to the current 'create incident' form.

**Comment by ManZzup** [comment]
This is completed
