### ISSUE TITLE
set police related inputs on create form

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#214]
**Is your feature request related to a problem? Please describe.**
need to set police related inputs on create form.

**Describe the solution you'd like**

1. list view input to add one or more 'Injured Party' (if complainer is not the casualty)
- name
- address
- political affiliation

2. list view input to add one or more 'Respondent'
- name
- address
- political affiliation

3. list view input to add one or more 'Detained Vehicles' with total 
- vehicle no
- Private / Government

4. Court details / court/ B No/ Complaint No.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by nshamit** [comment]
Ref No.4, can we change it to the following

**Court Details**
- Court Name:
- Court No:
- B No:
- Complaint No.

**Comment by MrClemRkz** [comment]
completed without court details.
