### ISSUE TITLE
District-wise report issues 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#231]
**Is your feature request related to a problem? Please describe.**
District-wise reports have some issues

**Describe the solution you'd like**

District Reports
- [x] 1.Ref Category, the word should read "Violence"not "Election Violence"
- [x] 2.Ref Subcategory, these are not showing. Category is showing 
- [x] 3.mode-wise, the total is showing but not the selected mode
- [x] 4.Need to change the 'Total No. of Incidents' to 'No. of incidents within the period (date/time) to (date/time)' for every report. The default should be 4PM from one date to 4PM on the next day. You need to code this into the reports as well so it does not have the number of incidents from 12.01AM of a date to 23.59PM of the same date. Remember date taken should be the logged date not the date of the incident itself. 
- [x] 5.Need to include another line 'Total No.of reported incidents'. This should be the total no. of incidents ever logged since the first date incidents were entered into the system. 
- [x] 6.Need to include a report which does analyzes total no. of incidents by date of incident (NOT date incident is logged) 

Basic Reports
- [x] 7.Need to remove district-wise from the drop-down now that you have a district-wise button
- [x] 8.Need to change the 'Total No. of Incidents' to 'No. of incidents within the period (date/time) to (date/time)' for every report. The default should be 4PM from one date to 4PM on the next day. You need to code this into the reports as well so it does not have the number of incidents from 12.01AM of a date to 23.59PM of the same date. Remember date taken should be the logged date not the date of the incident itself. 
- [x] 9.Need to include another line 'Total No.of reported incidents'. This should be the total no. of incidents ever logged since the first date. 
- [x] 10.Need to include a report which does analyzes total no. of incidents by date of incident (NOT date incident is logged) 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MrClemRkz** [comment]
this is complete.

**Comment by nshamit** [comment]
Feedback:

- Ref: all - Let's changed the total in the table to No. of Incidents Within the Stated Period. See if you can pull the date range there. If not, that's okay. 

- Ref: all - Let's change the total at the end to Total No. of Incidents Reported

- Ref: subcategorywise - Change subcategory format to Category-> Subcategory (list all subcategories form highest no. of incidents to lowest)

- Ref. categorywise report -

**Comment by nshamit** [comment]
I'll check the stuff that is in production now

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 11 12 35](https://user-images.githubusercontent.com/44461004/66731194-b8c3cc00-ee73-11e9-8f54-666ca73130a5.jpg)

- [ ] Ref image. The Other category should be at the bottom next to the total.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 11 20 33](https://user-images.githubusercontent.com/44461004/66731370-ab5b1180-ee74-11e9-8162-f427668441c1.jpg)

- [ ] 23. NONE is somewhere in the middle of the report. should be at the end of the report, near total.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 11 23 31](https://user-images.githubusercontent.com/44461004/66731453-173d7a00-ee75-11e9-898a-59477b141b7b.jpg)

- [ ] 24. The report needs to split into two categories

- [ ] 25. I would recommend putting the names of subcategories on the Y axis because they are longer than the names of the districts.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 11 26 02](https://user-images.githubusercontent.com/44461004/66731529-726f6c80-ee75-11e9-9929-6f2c31b215e6.jpg)

- [ ] 26. This has a NONE field again. It should be part of unassigned or part of a district. 

- [ ] 27. The alignment of the header boxes is sometimes center aligned, sometimes right aligned. Standardize this to center aligned.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 11 28 23](https://user-images.githubusercontent.com/44461004/66731592-c8dcab00-ee75-11e9-8318-4a3ac18f4a74.jpg)

- [ ] 28. This report is from the District-wise report for incidents date-wise. 
This does not have a district component

**Comment by nshamit** [comment]
![Screen Shot 2019-10-14 at 12 33 42](https://user-images.githubusercontent.com/44461004/66733946-e5311580-ee7e-11e9-845f-08c60480011d.jpg)

- [ ] 29. NONE appears here as well. Let's group this w/ unassigned.

**Comment by nshamit** [comment]
- [ ] 30. No. of incidents reported within the period
from 2019-10-13 16:00 to 2019-10-14 16:00 by District and Severity - This contains NONE here also.

**Comment by nshamit** [comment]
- [ ] 31. No. of incidents reported within the period
from 2019-10-13 16:00 to 2019-10-14 16:00 by District and Status - This contains NONE here also.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-15 at 09 45 45](https://user-images.githubusercontent.com/44461004/66799929-bd01ef00-ef30-11e9-8aad-a5a86bf1c8dd.jpg)

- [ ] 32. This has Other in the middle of 'Violence' and 'Violation'.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-15 at 09 56 39](https://user-images.githubusercontent.com/44461004/66800248-220a1480-ef32-11e9-8ddc-1a505b57ddce.jpg)

- [ ] 33. This has Other in the middle of the subcategory report.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-15 at 09 56 39](https://user-images.githubusercontent.com/44461004/66800362-8b8a2300-ef32-11e9-96c3-e4122c3bae0f.jpg)
34. Other is in the middle of this report. Should be the last category. 
This report is category and district-wise.

**Comment by MrClemRkz** [comment]
> ![Screen Shot 2019-10-14 at 11 28 23](https://user-images.githubusercontent.com/44461004/66731592-c8dcab00-ee75-11e9-8318-4a3ac18f4a74.jpg)
> 
> * [x]  28. This report is from the District-wise report for incidents date-wise.
>   This does not have a district component. I think we can have the date on the X axis, District name on the Y axis.

this is handled by disabling 'District wise' radio button. Therefore no such report will be created.

**Comment by umayangag** [comment]
I added disabling feature after the issue was creates.
