### ISSUE TITLE
Grafana dashboard issues

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#232]
**Is your feature request related to a problem? Please describe.**

- [ ] 1.Dashboard maps total no. of incidents to incident date, not logged date. 
- [ ] 2.Dashboard values are not adding up correctly 

**Describe the solution you'd like**

- [x] 3.Total no of incidents needs to be mapped w/ incident logged date not incident date. 

- [ ] 4."Total no. of incidents" needs to be changed to "Total no. of incidents for the time period" 

- [ ] 5.Need to have another panel which shows "Total no. of incidents logged". This shows total no. of incidents logged since the first day of entering incidents into the system. 

- [ ] 6.Can we can show the panels in a rectangular LCD view or have them auto-rotate to show different stats every few mins. so that we don't need to scroll up or down?

- [ ] 7.Ref photo of dashboard w/ Mode view showing. The total no. of incidents logged shows 48. However, the total of incidents in the mode panel totals to 42. 

- [ ] 8.When the district is drilled down, the total no. of incidents changes and the date range changes outside the range that the incidents were entered e.g. 2018-2020. 

- [ ] 9.Overlapping of text, cannot read the descriptions of the bars in "Violation of election law, top 5 categories'

![Mode](https://user-images.githubusercontent.com/44461004/66453623-9e0fe280-ea82-11e9-86c5-f8a8120931c6.jpeg)

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by MrClemRkz** [comment]
@mohamednizar @nshamit shall we close this and come up with a new issue for dashboards, as we discussed for new set of panels?

**Comment by MrClemRkz** [comment]
moved to new design.
