### ISSUE TITLE
Social media button required - additional mode on create incident form 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#236]
**Is your feature request related to a problem? Please describe.**
Include a separate button for social media to encompass all incidents which are input through WhatsApp, Viber, etc. This button should be an additional mode provided through the create incident form. 

**Describe the solution you'd like**
Include a separate button for social media to encompass all incidents which are input through WhatsApp, Viber, etc. 

Change the existing button stating "Tell Commission/FB" to "Tell Commission"

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MrClemRkz** [comment]
complete.
