### ISSUE TITLE
As Incident date is mandatory, include another option which states no date (can be radio button)

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#244]

**Comment by MrClemRkz** [comment]
Can't make incident 'occurred date' in both states. Therefore incident occurred date will be optional.

**Comment by MrClemRkz** [comment]
completed with testing on 'create form' , 'review form' and enter date on edit.

**Comment by MrClemRkz** [comment]
Need to enforce to check and checkbox if date is not given. Thereby to validate user it not giving a date consciously.

**Comment by lahiru94** [comment]
Fixed in pull request #356
