### ISSUE TITLE
EC - Create incident for the public user with social media connect

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#252]
**Is your feature request related to a problem? Please describe.**
The EC wants to put a link on the EC official website to a separate create incident form specifically for the public 

**Describe the solution you'd like**

- A link that is connected to the EC website which automatically opens up the create incident form. This form needs to have title, description, date, time, location information. 

- For WhatsApp, Viber and Facebook messages to have automatic replies configured which provides a link to the EC website so that they can fill the incident data directly. 

- For the EC's Facebook sites to have a message 'pinned to top' which contains a message and a link about the incident management system. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MrClemRkz** [comment]
completed without viber auto reply.
