### ISSUE TITLE
Include court information in create incident form

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#254]
**Is your feature request related to a problem? Please describe.**
Include court information in create incident form -this was not included in the original push w/ the police stuff. 

**Describe the solution you'd like**
Include the court information in the police view:

Court Name/ No:
B Report No:
Complaint No.

**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by MrClemRkz** [comment]
neglected.
