### ISSUE TITLE
Move incident logged date column to 2nd column in review screen 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#256]
**Is your feature request related to a problem? Please describe.**
The review tab is heavily used but doesnt not show the incident logged date.

**Describe the solution you'd like**
Add incident logged date column in the review screen for both normal and police incident review

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by nshamit** [comment]
![Screen Shot 2019-10-15 at 15 39 22](https://user-images.githubusercontent.com/44461004/66822518-028ae000-ef62-11e9-8549-84260a7731b1.jpg)

The logged date is the last column. Can we make this the 2nd column.

**Comment by ManZzup** [comment]
29/10/2019

**Comment by MrClemRkz** [comment]
done.
