### ISSUE TITLE
reports - need to select one or more incident type/s

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#259]
**Is your feature request related to a problem? Please describe.**
need to select one or more incident type/s

**Describe the solution you'd like**
checkboxes to select current incident types ['Compliant', 'Inquiry'] for the reports.

**Describe alternatives you've considered**
any other better UX suggestions are welcome.

**Additional context**
none

**Comment by umayangag** [comment]
incident type selection feature added
