### ISSUE TITLE
Grafana dashboard - shorter refresh time

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#267]
**Is your feature request related to a problem? Please describe.**
It took 15 mins to refresh the logged incident values. The manager in charge was not happy about the delay. She was preparing the 4pm report and the values we queried and gave her did not sync w/ the dashboard values. 

**Describe the solution you'd like**
5 second refresh or as short a time as possible. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by jayanath1987** [comment]
Default Time Period is set to 4PM to 4PM and refresh time also set 5 Seconds.

**Comment by MrClemRkz** [comment]
> Default Time Period is set to 4PM to 4PM and refresh time also set 5 Seconds.

is it selectable??

**Comment by jayanath1987** [comment]
It has been set as the default option, but we don't have a separate select link to it. Otherwise, we have to make code changes on grafana and build our own fork.
