### ISSUE TITLE
New report format 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#270]
**Is your feature request related to a problem? Please describe.**
Need a new report format to help the EC show higher leadership that issues are moving along the lifecycle and are being resolved. 

**Describe the solution you'd like**
Report to be called Detailed Status

- New/ Unverified
- In progress (Verified, Action pending, Action taken, Advice requested, Advice Given - these need to be put together). 
- Closed 
- Invalidated 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by MrClemRkz** [comment]
This is considered as system wide status updated and therefore it is been covered by Grafana Dashboards.
If certain leadership is assigned to particular incident/s will be notified on their home pages on those regards.
