### ISSUE TITLE
Add 'Assigned from' and and 'Assigned to' column to police 'review incident' screen 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#273]
**Is your feature request related to a problem? Please describe.**
Police will need an easy way of understanding which incidents they have been assigned to and which ones they are assigning to other police divisions etc. 

**Describe the solution you'd like**

- [x] - 1.  Add 'Assigned from' and and 'Assigned to' column to police 'review incident' screen 
- [x] - 2. Assigned from will be EC or Police HQ. 
- [x] - 3. Assigned to will be EC, Police HQ or Police Division 'X'
- [ ] - 4. Full text search of review screen + advanced search and filters. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ManZzup** [comment]
12/11/2019

**Comment by ManZzup** [comment]
@MrClemRkz clarification needed as well

**Comment by ManZzup** [comment]
Fixed without full text search, current database doesn't support full text search
