### ISSUE TITLE
Assign an issue to Police HQ or Police Division (w/ name of division) 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#274]
**Is your feature request related to a problem? Please describe.**
We should allow the police to track where they have assigned an issue. 

**Describe the solution you'd like**
Assign an issue to Police HQ or Police Division (w/ name of division). 
EC has given LSF a full list of police divisions to input into the assignee section.  

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ManZzup** [comment]
Will be completed with #346

**Comment by ManZzup** [comment]
Fixed.
