### ISSUE TITLE
Police can request 'Close incident' 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#275]
**Is your feature request related to a problem? Please describe.**
If the incident only required police action, there is a need for the police to initiate closure proceedings by requesting 'Close Incident'

**Describe the solution you'd like**
Include action, same as in EC side, to request 'Close Incident' to be approved by EC Manager level/ above. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ManZzup** [comment]
Integrate into external action workflow
05/11/2019

**Comment by ManZzup** [comment]
Temporary solution is to use the comment feature to request closing the incident
