### ISSUE TITLE
Incident Review - Incident History Log- Action taken date not mentioned,  only time is displayed 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#282]
**Describe the bug**
Incident History Log-  Date not mentioned only time displayed hence , can't figure out on which date the particular action is taken

**Expected behavior**
Action taken date also should be displayed under incident history log

**Screenshots**
![date_missing](https://user-images.githubusercontent.com/56617308/66883043-22fe7d00-efea-11e9-943f-e4ef466c7951.png)

**Comment by MrClemRkz** [comment]
issue fixed.
