### ISSUE TITLE
Incident View / Incident List -  "Last Action at"  column does not update

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#285]
**Describe the bug**
Incident View / Incident List -  "Last Action at"  column does not update

**Expected behavior**
"Last Action at" Field should be properly updated as per the last action occurrence

**Screenshots**
![moment](https://user-images.githubusercontent.com/56617308/66890116-8d231c00-f002-11e9-9c34-ef55a6c1fa46.png)

**Comment by nshamit** [comment]
No longer required as a functionality
