### ISSUE TITLE
Return validation message as "Server Error" when user tries to escalate

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/IncidentManagement#286]
**Describe the bug**
Return validation message as "Server Error" when user tries to escalate

**To Reproduce**
1. login as "Manager"
2. Try to escalate verified incident
3. Validation message returned as "Error"

![Escalate](https://user-images.githubusercontent.com/56621237/66890418-c60fc080-f003-11e9-98f9-ccac23ee85a1.JPG)

**Comment by MrClemRkz** [comment]
fixed.
