### ISSUE TITLE
Reports- Bookmarks/ No of Incidents are not functioning

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/IncidentManagement#288]
Reports- Bookmarks/ No of Incidents are not functioning

![Bookmark](https://user-images.githubusercontent.com/56621237/66890832-0885cd00-f005-11e9-9149-6fb683026097.JPG)

**Comment by nshamit** [comment]
@Chathurikaweerasinghe - Can you provide more clarification here.

**Comment by Chathurikaweerasinghe** [comment]
Options under bookmark of the generated report is not working. 
 I have highlighted in screenshot


![Bookmark_2](https://user-images.githubusercontent.com/56621237/66895010-6f0fe880-f00f-11e9-8ec8-5528e45f07f1.jpg)
