### ISSUE TITLE
Create Incident -There is no restriction on the size of the file can be uploaded.

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#290]
**Describe the bug**
Currently there is no any restriction on the size of the file can be uploaded.This can lead to additional overhead as this is going to be used by large number of users.

**Expected behavior**
The maximum file  size that can be uploaded should be restricted.

**Screenshots**
![file upload](https://user-images.githubusercontent.com/56617308/66891118-e17bcb00-f005-11e9-804f-d152dda7679d.JPG)

**Comment by ManZzup** [comment]
Please advice on the file size limit per file

**Comment by ManZzup** [comment]
Fix loading as well
29/10/2019

**Comment by lahiru94** [comment]
100MB total file size limit added for all file uploads in the system.
