### ISSUE TITLE
When user refer to organization as “other” and workflow displays as “NULL”

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/IncidentManagement#291]
**Describe the bug**
When user refer to organization as “other” and workflow displays as “NULL”

![refer to organization](https://user-images.githubusercontent.com/56621237/66891190-14be5a00-f006-11e9-80b1-1ac8c9658c71.JPG)

**Comment by MrClemRkz** [comment]
estimation: 5hrs

**Comment by MrClemRkz** [comment]
done.
