### ISSUE TITLE
Review - Text Search - Doesn't work when navigated to review screen

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#294]
**Describe the bug**
Review - Text Search - Cannot search by incident ID , An empty list loaded (cannot search by full incident ID) 

**Expected behavior**
Proper record should be filtered according to the incident ID

**Screenshots**
![incidentid](https://user-images.githubusercontent.com/56617308/66892421-484eb380-f009-11e9-9614-da64732869fc.JPG)

**Comment by ManZzup** [comment]
05/11/2019

**Comment by ManZzup** [comment]
Fixed.
