### ISSUE TITLE
Workflow-As per the requirement Complaint coordinator is the one who can verify incidents but Data entry user also given the permission to verify the complaint

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#295]
**Describe the bug**
As per the requirement Complaint coordinator is the one who can verify incidents but Data entry user also given the permission to verify the complaint

**Expected behavior**
Verify option should not be available for data entry user

**Screenshots**
![verify](https://user-images.githubusercontent.com/56617308/66892708-0a9e5a80-f00a-11e9-9398-f2e055e2b562.JPG)

**Comment by MrClemRkz** [comment]
this is obsolete, thus closed.
