### ISSUE TITLE
Some of the mandatory fields are not marked properly. User cannot submit create form successfully (Ex: Severity)

### ISSUE THREAD

**Issue by Chathurikaweerasinghe** [ECLK/IncidentManagement#296]
**Describe the bug**
Some of the mandatory fields are not marked properly. So user cannot submit create form successfully (Ex: Severity)

**Expected behavior**
Mandatory fields should mark with asterisk symbol"*" in order to identify mandatory fields properly and should return proper validation message when user fails to fill

**Comment by MrClemRkz** [comment]
completed with PR #348
