### ISSUE TITLE
Workflow-There is no option given for managers to reopen an incident

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#298]
**Describe the bug**
Workflow-There is no option given for managers to reopen an incident that has been closed if new information has surfaced related to the scenario  or a new complaint has been connected to it.

**Expected behavior**
There should be an option to re-open a closed incident if  something new comes up related to the incident.

**Comment by ManZzup** [comment]
Change status to REOPENED 
05/11/2019

**Comment by ManZzup** [comment]
Feature added
