### ISSUE TITLE
Workflow-Complaint Coordinator user (EC) , Can not verify an incident is a valid complaint or is a bogus complaint

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#299]
**Describe the bug**
Workflow-Complaint Coordinator user (EC) , should be able to verify an incident is a valid complaint or is a bogus complaint, But only verify option is available. Nothing can be done [No status change available ]if the incident is bogus or invalid one 

**Expected behavior**
There should be an state to be updated and based on that , should be able to close the incident if it is a bogus or invalid one

**Comment by nshamit** [comment]
relates to #264
