### ISSUE TITLE
Login- No Error message displayed when try to login with invalid credentials  

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#304]
**Describe the bug**
No Error message displayed when try to login with invalid credentials  

**Expected behavior**
Proper error message should display 

**Screenshots**
![Noerror](https://user-images.githubusercontent.com/56617308/66896317-34f41600-f012-11e9-8032-c733f58c450d.png)

**Comment by MrClemRkz** [comment]
completed on PR #347 .
