### ISSUE TITLE
Sinhala Unicode messed up when exported to PDF

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#306]
**Describe the bug**
Sinhala Unicode messed up when exported to ( CSV / PDF ) - Displaying garbage characters

**Expected behavior**
Font should be encoded properly

**Comment by nshamit** [comment]
relates to #235

**Comment by ManZzup** [comment]
29/10/2019

**Comment by ManZzup** [comment]
Nicely fixed by @aijdissanayake

**Comment by aijdissanayake** [comment]
GG
