### ISSUE TITLE
Data Entry User - Can't view the list incident entered [ Except the current incident ]

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#310]
**Describe the bug**
Data Entry User - Can't view the list incident entered [ Except the current incident ]

**To Reproduce**
Incidents List should be displayed

**Comment by nshamit** [comment]
As per the requirement, the need was to have data entry users focus on getting the data into the system as quickly as possible. 

The complaint coordinator role is able to view, edit, verify and review the list of incidents.
