### ISSUE TITLE
EC Complaint Manager, Should  be able to set roles and permissions for his  staff. But when logged in as a manager this functionality is not available 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#313]
**Describe the bug**
EC Complaint Manager, Should  be able to set roles and permissions for his  staff. But when logged in as a manager this functionality is not available 

**Expected behavior**
EC Complaint Manager functionality should be available.

**Comment by nshamit** [comment]
to be done through identity server.
