### ISSUE TITLE
Validation errors are not  positioned next to the field with the error

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#314]
**Describe the bug**
Validation errors are not  positioned next to the field with the error so the user knows which field the error relates to.

**Expected behavior**
Validation errors should be positioned next to the field 

**Screenshots**
![validation msg](https://user-images.githubusercontent.com/56617308/66911891-118b9400-f02f-11e9-868c-26135d86ead1.png)

**Comment by MrClemRkz** [comment]
fixed in PR #348
