### ISSUE TITLE
Complaint Coordinator should  to be able to open up links, audio, video and images in a pop up rather than having to download the attachments 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#316]
**Describe the bug**
Complaint Coordinator should  to be able to open up links, audio, video and images in a pop up rather than having to download the attachments but at the moment every attachment is getting downloaded.

**Expected behavior**
Complaint Coordinator should  to be able to open up links, audio, video and images in a pop up rather than having to download the attachments

**Comment by nshamit** [comment]
relates to #170
