### ISSUE TITLE
EC Users should be able to categorize an incident complained as not related to the election

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#317]
**Describe the bug**
EC Users should be able to categorize an incident complained as not related to the election, but still keep the details in the system for further reference By selecting 'Other' from election type.But there is no "Other" type loaded under election type

**Expected behavior**
EC Users should be able to categorize an incident complained as not related to the election

**Comment by nshamit** [comment]
relates to #264
