### ISSUE TITLE
UI issue on 'refer to organization' modal

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#319]
**Describe the bug**
UI issue on 'refer to organization' modal

**Screenshots**
![Screen Shot 2019-10-16 at 9 35 49 PM](https://user-images.githubusercontent.com/16492984/66938026-1287ea00-f05e-11e9-8e12-47df904b5b99.png)
![Screen Shot 2019-10-16 at 9 35 41 PM](https://user-images.githubusercontent.com/16492984/66938027-1287ea00-f05e-11e9-9f33-95e7704fe6b4.png)

**Comment by ManZzup** [comment]
29/10/2019

**Comment by MrClemRkz** [comment]
completed.
