### ISSUE TITLE
Dashboard total issue

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#321]
**Is your feature request related to a problem? Please describe.**

Dashboard totals are not adding up

**Describe the solution you'd like**

- [ ] 1. Mode category total does not add up

**Describe alternatives you've considered**
no
**Additional context**
no

**Comment by nshamit** [comment]
relates to #231

**Comment by MrClemRkz** [comment]
add 'unassigned' count, when no category or mode.
- [ ] unassigned for category
- [ ] unassigned for mode

**Comment by jayanath1987** [comment]
Updated to repo

**Comment by nshamit** [comment]
@MrClemRkz please confirm that this is okay and that this issue can be closed.

**Comment by jayanath1987** [comment]
@MrClemRkz  Please Update 0 value in Prod

**Comment by MrClemRkz** [comment]
completed.
