### ISSUE TITLE
Complainer creates an incident

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#33]
## User Story
AS A Complainer, I WANT to add and incident record to the system SO THAT it can be processed.

### (1) Visit Home page
[homepage screen]
![homepage_complainer](https://user-images.githubusercontent.com/16492984/54273296-a61aa900-45ab-11e9-8be5-5a8a1ed74c73.png)

### (2) Click on card 'Report an Incident' and view the form to collect Incident information.
[create incident - step 1]
![guest_create_incident_step_1](https://user-images.githubusercontent.com/16492984/54273313-ac108a00-45ab-11e9-8d55-2b97e6827a9b.png)

### (3) Click button 'Next' and view the form to collect Incident location information.
[create incident - step 2]
![admin_create_incident_step_2](https://user-images.githubusercontent.com/16492984/54386449-fb93aa80-46be-11e9-837c-515ba992ad33.png)

### (4) Click button 'Next' and view the form to collect contact information of the reporter.
[create incident - step 3]
![guest_create_incident_step_3](https://user-images.githubusercontent.com/16492984/54273338-b763b580-45ab-11e9-9786-7f206501b1fa.png)

### (5) Click button 'Next' and view the full view of all collected information for review purpose.
[create incident - step 4]
![guest_create_incident_step_4](https://user-images.githubusercontent.com/16492984/54273348-bc286980-45ab-11e9-9d00-34bf5f3f062f.png)

### (6) Click button 'Submit' and get prompted for adding more Incident information or not.
[user prompt for add more incidents screen]
![admin_create_incident_step_success](https://user-images.githubusercontent.com/16492984/54273378-c8142b80-45ab-11e9-8cb1-8e4312b5ebb4.png)

**Comment by ManZzup** [comment]
### Backend APIs

- [ ] Create incident

**Comment by ManZzup** [comment]
Once Finished, incident title and description must not change
