### ISSUE TITLE
When reporting incident, date/time field is reset if time is not explicitly set

### ISSUE THREAD

**Issue by ramdesh** [ECLK/IncidentManagement#388]
**Describe the bug**
When reporting an incident, the date/time field sets to empty values by default. The date picker only allows to select a date, and if the user moves focus from the date picker field without explicitly defining a time, it resets to the empty values.

**To Reproduce**
1. Go to 'Create Incident'
2. Select a date from the date picker
3. Click anywhere outside the date picker
4. The date field is reset to the default values (mm/dd/yyyy etc)

**Expected behavior**
The date should not reset when focus is lost on the field without a time being selected.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 79

**Comment by MrClemRkz** [comment]
on creation of an incident, we make user to select occurance value and with that to validate the selection of the date. What we can expect to do is, set default time when date is selected. May be selected time would be '00:00 am'??

**Comment by MrClemRkz** [comment]
estimation: 8hrs

**Comment by ruhaim** [comment]
I am not sure, what date time component is being used here, but could we use something like http://projects.wojtekmaj.pl/react-datetime-picker/ which has the date AND time incorporated into the component

**Comment by MrClemRkz** [comment]
completed and merged.
