### ISSUE TITLE
frontend code refactor

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#393]

**Comment by ManZzup** [comment]
Planned refactoring for the frontend app
==============================

## Structure

- Fix directory structure to break into proper modules
- New modules to be created - event
- Clean up app sources and remove commented parts

## Redux

- Enforce redux toolkit app wide
- Fix action creators 
- Clean redundant actions 

## Other

-  Move all class components to functions with hooks
- Add errors, loading and confirmation app wide. The loading hook need to be used

**Comment by MrClemRkz** [comment]
estimation: 8hrs

**Comment by ManZzup** [comment]
Remaining task - convert SharedReducer / actions to toolkit syntax

**Comment by MrClemRkz** [comment]
current issues (13-02-2020)

- [ ] verify workflow goes blank
- [ ] Assigned to and Assigned from is not set.

**Comment by ManZzup** [comment]
- [ ] Convert shared reducer to toolkit
