### ISSUE TITLE
View single incident for review

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#40]
## User Story
AS A Complaint Coordinator, I WANT to view selected incident from the list SO THAT I can read the details of that particular incident.

### (1) View table list of Incidents
![list_incidents_new](https://user-images.githubusercontent.com/16492984/54696219-74788380-4b51-11e9-8a7f-5ffa6386c5ce.png)

### (2) Click on Button-Icon-edit view the incident in Tab-View.
[single-view-incident]
![single_incident_review](https://user-images.githubusercontent.com/16492984/57789339-58aaeb80-7756-11e9-93a1-75f9422916bb.png)

**Comment by ManZzup** [comment]
testing a comment

**Comment by ManZzup** [comment]
Closed.
