### ISSUE TITLE
on edit, previous set date time is not shown

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#406]
**Describe the bug**
previous set date time is not shown when goto edit incident information

**To Reproduce**
1. Go to an single incident view page.
2. Click on edit for edit process.
3. Scroll down to 'Incident date' and 'Incident time'

**Expected behavior**
previously set data and time should be shown when goes to

**Comment by ruhaim** [comment]
Created a pull request for this

**Comment by MrClemRkz** [comment]
> Created a pull request for this #407

Thanks I'll merge it.

**Comment by MrClemRkz** [comment]
this is completed by ruhim.
