### ISSUE TITLE
search component to be revamped

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#409]
**Describe the bug**
Search does not work as it should.

**To Reproduce**
1. Go to 'review' menu
2. try 'search text' on ID, title or description
3. see if related inicdents are listed.

**Expected behavior**
associated incident/s shown to the given search text

**Additional context**
Try search with filters as well.

**Comment by ramdesh** [comment]
Working on this.

**Comment by ramdesh** [comment]
@MrClemRkz text-based search works as required. Were there specific filters you were referring to?

**Comment by MrClemRkz** [comment]
> @MrClemRkz text-based search works as required. Were there specific filters you were referring to?

@ramdesh yes. need to fix the filters.

**Comment by ramdesh** [comment]
@MrClemRkz Severity is captured in the incident form but not displayed anywhere. Is this as intended?

**Comment by ramdesh** [comment]
`Category` is the only filter that is not being applied. Will fix.

**Comment by MrClemRkz** [comment]
@ramdesh in the current discussions we are not going to show severity on lists as a column. but we definitely need to show it, when an incident is open (in the basic information tab, latter section)

**Comment by MrClemRkz** [comment]
tested.
