### ISSUE TITLE
report view to be revamped

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#410]
**feature request**
A view to adhere to to Generate Printable Daily Reports for Complaints
- Daily Summary (Districts)
- Daily Summary (Complaint Management Center)
- Total Summary of Complaints

suggested UI:
- 3 links or buttons under the a section called 'Daily Reports - Complaints'
- upon click will bring the pdf and open it on a new tab.
- buttons may have a linear progress until the pdf is arrived and opened on a new tab.

(what's mentioned above is a suggested one. any different UI/UX is also fine.)

**Comment by TRomesh** [comment]
I would like to work on this task

**Comment by MrClemRkz** [comment]
awesome. please accept the invitation we have sent you, to add to you the repo.

observe a bit on current report view. I'm thinking something minimalist. 

User scenario is that, daily at 4pm EC need to send an report to media summarizing the day's incident records. So each daily report by default collects incidents from previous day 4pm to current date 4pm.

**Comment by MrClemRkz** [comment]
this is completed
