### ISSUE TITLE
Separate review screen for inquiry

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#411]
**Changes need to be made:** 
1. Review button - include a drop down for Review inquiry and Review complaint. 
2. Include clear title at the top which says Review Inquries or Review Complaints (title in large font)
3. New screen for Review Inquiry
4. Remove column for description 
5. Add column for institution (which can be filtered)
6. Add column for Letter date and Received date
7. Change category data
8. Remove assigned from and to. 
9. Remove type (complaint or incident)
10. Move status/decision to end column. 

**These columns should be present:** 
1. Reference number 
2. Received date
3. Letter date
4. Mode of receipt
5. Category
6. Institution 
7. Title
8. Decision

**Comment by ramdesh** [comment]
@MrClemRkz it seems that there is only an `incidents` endpoint on the API, do we need to create a separate `inquiries` endpoint for this? I see that on fetching the `incidents` API there is an `incidentType` field that gets populated as `INQUIRY` if it is an inquiry. Do we use this to differentiate between the two on the UI or do we need to go ahead and create a separate `inquries` endpoint? I can do either one based on your decision.

**Comment by MrClemRkz** [comment]
@ramdesh I'm thinking to go ahead with same endpoint for both inquires and complaints. Do you see any pitfalls in that approach?

**Comment by ramdesh** [comment]
I'd say it's not the best in terms of design but in the interest of time, I think it's fine to go ahead with the same endpoint.

**Comment by ramdesh** [comment]
@MrClemRkz what does `Mode of receipt` and `Institution` map to in the API response?

**Comment by ramdesh** [comment]
Also how do we map the `Category` field? API response just has a number.

**Comment by ramdesh** [comment]
Mapped `Mode of receipt` to `infoChannel`. How do I map `Institution` ?

**Comment by ramdesh** [comment]
Added #441 anticipating change requests.

**Comment by MrClemRkz** [comment]
> Mapped `Mode of receipt` to `infoChannel`. How do I map `Institution` ?

will have a dummy api data set return at the moment until the location-service is up.
