### ISSUE TITLE
Add location information 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#412]
Information from Shanuka/ Sanjeewa on locations and update "Institution" drop downs. 
Need to be able to search for a few letters and get a suggestion also. 
Need to be able to type fully the institution in the event the name is wrong or not included - example "Other" and blank column. 

1. List of 16 ministries 
2. List of commissionsList of local govt 
3. List of Provincial councils
4. List of departments / institutions
5. List of branches
6. List of district centers
7. Get API from Shanuka / Location services (Sanjeewa)

**Comment by MrClemRkz** [comment]
this is to be populated via external service endpoint. 

@paramids can you make this dropdown searchable?

**Comment by paramids** [comment]
@MrClemRkz .I can use semantic ui react for it... To get everything in perspective, I assume that the data would be provided from the REST API backend. What I need to do is to load the data from a rest call and display it on a drop down list which is searchable..? Also, should this be implemented as a separate module or should I use incident-filing /incident module ?

**Comment by MrClemRkz** [comment]
>  What I need to do is to load the data from a rest call and display it on a drop down list which is searchable..? 

yes.

> Also, should this be implemented as a separate module or should I use incident-filing /incident module ?

Well it doesn't matter as long as fomik can pick the value.

**Comment by MrClemRkz** [comment]
- acheived it via json file until the location-service is ready to run. 
- on the form, we use a seperate textbox with auto-suggest until the Material-UI version migration to v4.
