### ISSUE TITLE
Create inquiry slip

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#414]
The inquiry slip is generated after the inquiry information is input into the system. 

This is then printed on to an A4 sheet and stapled w/ the original inquiry letter and will be placed in a file w/ the inquiry information. 

The slip needs to contain the following information:

1. Reference number 
2. Date
3. Category Code
4. Category Name 
5. Institute Name

Slip has to be A4 size or smaller. 

- [x] template format: https://github.com/ECLK/pdf-service/issues/17
- [x] backend integration

**Comment by MrClemRkz** [comment]
completed and merged.
