### ISSUE TITLE
Add radio button/ select, at the comment area when giving resolution

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#415]
Statuses are (more like resolution statuses):

1. Approved
2. Approved w/ condition
3. Not Approved 
4. Requested further information 

When commenting you can choose whether you are giving an 'incident resolution'. Here, user will be prompted to choose one of the statuses to select as the comment.

This prompt could be dropbox, radio button, buttons or even popup box (like modal). This is only required when the incident is an inquiry.

**Comment by MrClemRkz** [comment]
thanks @hsvikum it works perfectly.
