### ISSUE TITLE
Changes to create form

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#417]
1. Change 'incident mode of receipt' to 'mode of receipt'
2. Remove 'responsible political party' and change this into "Against who"
3. Check if file upload does multiple files 
4. Change order (switch) police station and division

**Comment by ramdesh** [comment]
I can take this on

**Comment by ramdesh** [comment]
- [x] Change 'incident mode of receipt' to 'mode of receipt'
- [x] Remove 'responsible political party' and change this into "Against who"
- [x] Check if file upload does multiple files - Checked with `*.pdf`, `*.txt` , `*.png` and `*.jpg` at the same time and with different combinations
- [x] Change order (switch) police station and division

**Comment by ramdesh** [comment]
Fixed by #432
