### ISSUE TITLE
Escalate review on Incident to upper level roles

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#42]
## User Story
AS A Complaint Manager, I WANT to request for an advice from Chief Complaint Coordinator.

**Comment by ManZzup** [comment]
Escalation, request for advice workflows needed @MrClemRkz

**Comment by MrClemRkz** [comment]
> Escalation, request for advice workflows needed @MrClemRkz

## Escalation - upon modal view:
select particular user or user role -> add comment if necessary -> submit.

## request for advice
check #44

**Comment by ManZzup** [comment]
Merged to #117

**Comment by ManZzup** [comment]
Merged to #117
