### ISSUE TITLE
Create reference number for inquiries

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#420]
Convention is:

 Date/ Sequence no. (0001, 0002 etc) / Category Number/ Institution Number

Example: 
2020224/0001/1/12

**Comment by pasanchamikara** [comment]
A few questions

1. In the `Incident` model there is the attribute `category`, for the json request which is to come, is the `category` sent as a `code` (As which is at the `code` on `Category` model) or the full category name (Which could be either of the trilingual I believe) 
2. A side question to the 1st one, as per the format mentioned above I assume it is not reliant with the Category code which is specified in the model `Category`, is it a mistake, or do we need to get the value of the Auto increment Id field (Suspected)
3.  What does the institution number exactly refer to? I can see that there are 2 attributed `polling_station` and `police_station`?

**Comment by MrClemRkz** [comment]
1. it's the `id` is sent on the post request.
2. auto increment field is the `id` of `Category`. But for refID generation better use the `code` of `Category` model.
3. There will be new field as `institute`. Idea was to pull the code number of the institute for the refID.

**Comment by pasanchamikara** [comment]
`PR` created https://github.com/ECLK/IncidentManagement/pull/440
