### ISSUE TITLE
Allow users to search for duplicate inquiries before adding a new inquiry into the system 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#422]
- On the review inquiry screen, users need to filter the institution and isolate only the inquiries that are related to a certain ministry or organization  - for example, Ministry of Finance. 

- They should then be able to check the "Letter Date" field and the "Title" field to check if the letter they have just received from someone in person is a duplicate letter which was sent earlier by fax. Sending a letter via fax, postal mail, in person on the same matter is common. 

- They should be be able to click and view the inquiry contents in the list. If there is a duplicate letter, they should be able to log the details of the newly received letter in the same inquiry. 
For example, there is an inquiry, and the letter was received by Fax. After this, another letter on the same matter, w/ the same title is received by post. The information should be logged in the same inquiry. 

- [x] frontend component
- [x] backend api

**Comment by MrClemRkz** [comment]
completed and merged.
