### ISSUE TITLE
Referring / Assigning an incident to the district 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#425]
**Allow users to refer/ assign an incident to the district** 

- User can refer an issue to the district EC for follow up, for example request information etc. 
- District can update the incident 
- Allow users who have been assigned the incident to include updates, upload attachments etc. 
- User can refer an issue to the district EC for follow up, for example request information etc. 
- District can update the incident 
- Allow users who have been assigned the incident to include updates, upload attachments etc.

**Comment by MrClemRkz** [comment]
This is fixed.
