### ISSUE TITLE
Allow users to check if a complaint has already been filed - to ensure there is no duplicate complaint logged. 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#427]
- On the review complaints screen, users need to be able to check there are no duplicate incidents by a dynamic search ...you type in a few letters and get suggestions on incidents. 

- Users should also be able to search according to incident date, title, category and other fields to ensure they do not input a duplicate incident.

**Comment by MrClemRkz** [comment]
done
