### ISSUE TITLE
List incidents for Assigned and Requested for advice

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#43]
## User Story
AS A Chief Complaint Coordinator, I WANT to list all advice required incidents list viewed, SO THAT I can review them.

**Comment by ManZzup** [comment]
Escalation, request for advice workflows needed @MrClemRkz

**Comment by MrClemRkz** [comment]
with reference to: https://github.com/ECLK/IncidentManagement/issues/95#issuecomment-507717687

@lahiru94 you mean, you need users with roles from Identity server? or mockup user list at the moment?

**Comment by ManZzup** [comment]
Done by https://github.com/ECLK/IncidentManagement/commit/5f968e18990ce5cfce6392c5407c3a71aedfa102
