### ISSUE TITLE
Single view of escalated Incident

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#44]
## User Story
AS A Chief Complaint Coordinator, I WANT to view all details of an incident, SO THAT I can analyze and submit my advice (comment) to the particular complaint.

**Comment by ManZzup** [comment]
This encapsulated the UIs / workflow for
1. request for advice 
2. confirm verification 
dialog

Workflow needed @MrClemRkz

**Comment by MrClemRkz** [comment]
Workflows as follows:

1. upon modal dialog:
must select particular person or role -> set comment -> submit.
- default comment is '{actioned person} has request for advice from {particular assigned person/role}'.

2. upon modal dialog:
particular person / role, must set a comment / take an action on the incident -> done.
- at this particular moment incident is waiting for a update at the comment trail on the incident from assigned particular person / role. 
- when action is taken, it'll automatically assigned back to the previous assignee.

**Comment by ManZzup** [comment]
Merged to #117

**Comment by ManZzup** [comment]
Merged to #117
