### ISSUE TITLE
Set assigned external entity information of an Incident

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#46]
## User Story (1)
AS A Complaint Manager, I WANT to store entity's information against complaint(s) whom got received the particular complaint.

## User Story (2)
AS A Complaint Manager, I WANT to store legal's information SO THAT I can log which complaints are being followed by which legal(s).

**Comment by ManZzup** [comment]
@MrClemRkz workflow advice needed

**Comment by MrClemRkz** [comment]
> @MrClemRkz workflow advice needed

External entity on the context is mostly any user(entity) not found on the system. Therefore we need to add information of particular person as a comment.

In the body of the comment it should contain following information:
- name
- contact number
- contact email
- type ( this could be any like police, legals, party etc.)
- comment (reason or type of assignment)

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] workflow UI
- [ ] backend API

**Comment by MrClemRkz** [comment]
relates to #117

**Comment by ManZzup** [comment]
we should close this right?

**Comment by MrClemRkz** [comment]
guess we could, since this includes in #117.
