### ISSUE TITLE
Advanced search for Inquiries and complaints enabled 

### ISSUE THREAD

**Issue by nshamit** [ECLK/IncidentManagement#461]
### Filter by
- [x] district
- [x] status

**Comment by ramdesh** [comment]
Currently, advanced search has the following fields:
* Status
* Response time
* Severity
* Category
* Start time + end time
* Institution

Do we keep these in place or only stick to district and status?

**Comment by MrClemRkz** [comment]
at the moment we can stick only into:
- district
- status
- category
- start datetime to end datetime of created date
- severity [high(10-8), medium(7-4), low(3-1)]
- institution (for inquiry only)

**Comment by MrClemRkz** [comment]
this is complete.
