### ISSUE TITLE
Escalate to external entities

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#47]
## User Story 
AS A Complaint Manager, I WANT to set incident as 'further action needed' SO THAT I can transfer complaint(s) to legals.

**Comment by ManZzup** [comment]
@MrClemRkz is this another Status flag?

**Comment by MrClemRkz** [comment]
> @MrClemRkz is this another Status flag?

This will be on hold for the moment. Same scenario will be covered with action status of 'action pending'. What's concerned is where if an incident had to go beyond due date and time, will have to have a way to identify those without having to read about the incident from top to bottom.

For this one method could be having a separate status. Yet that could confuse the usage, and misuse it.

**Comment by ManZzup** [comment]
1. Select "Take action button"
2. Shows dialog with inputs -> Entity, Name, Contact, Reason
3. Submit changes the incident status to Action Pending
4. Event is created

**Comment by ManZzup** [comment]
Merged to #117
