### ISSUE TITLE
Complaint -EC Data Entry User - Create Incident - When user clicked on submit ,no success message displayed , when clicked again invalid validation message displayed 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#484]
**Describe the bug**
Create Incident - When user clicked on submit ,no success message displayed , when clicked again invalid validation message displayed 

**To Reproduce**
1. Login as EC Data entry user 
2. Click on create and fill the details as displayed in the screenshot 1
3. Scroll down to 'submit' and click 
4. check the outcome
5. Again click 'submit' 
6. See the message 

**Expected behavior**
when click on submit , the system should save the incident and display a success message

**Actual Behavior**
Once clicked on submit nothing happens , the again user click on submit there is an invalid message appeared as "Submit without occurred date ? " [ But occurred date is already available ] 
![Screenshot1](https://user-images.githubusercontent.com/56617308/77288783-97a6b780-6cfe-11ea-94cc-77c223e9c2a0.png)
![Screenshot2](https://user-images.githubusercontent.com/56617308/77288786-9aa1a800-6cfe-11ea-8a61-be49715d91b7.png)

**Comment by MrClemRkz** [comment]
## Note for devs: 
This is fixed when restarted.

**Comment by MrClemRkz** [comment]
this is fixed.
