### ISSUE TITLE
Complaint -When an incident is edited , incident date and incident time fields becomes empty  

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#485]
**Describe the bug**
When an incident is edited , incident date and incident time fields becomes empty  

**To Reproduce**
1. Create an incident by adding necessary  details
2. Once done click on 'Edit' and change few details [ Other than incident date and incident time ]
3. Again click on 'Submit'
4. See the  Message

**Expected behavior**
Information should be updated properly

**Actual Behavior **
When updated , incident date and incident time fields becomes empty

**Comment by MrClemRkz** [comment]
this is completed.
