### ISSUE TITLE
Complaint - Complainer details not available when an incident is edited 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#486]
**Describe the bug**
Complainer details not available when an incident is edited 

**To Reproduce**
1. Create an incident with complainer details
2. Again edit the incident location and save
3. now check whether contact information available

**Expected behavior**
Contact information should remain unchanged

**Actual Result**
Contact information unavailable once incident is edited 

![1](https://user-images.githubusercontent.com/56617308/77292339-1e12c780-6d06-11ea-8a63-fccb9a69232c.png)
![2](https://user-images.githubusercontent.com/56617308/77292343-20752180-6d06-11ea-8352-c1d3cf1913db.png)

**Comment by MrClemRkz** [comment]
tested and completed.
