### ISSUE TITLE
Complaint - Refer to Organization entity - selected options overlapped with  place holder 

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#488]
**Describe the bug**
Refer to Organization entity - selected options overlapped with  place holder 

**Screenshots**
![policeassignment](https://user-images.githubusercontent.com/56617308/77294890-012cc300-6d0b-11ea-9504-16d30193b38c.png)

**Comment by MrClemRkz** [comment]
completed.
