### ISSUE TITLE
Complaint - EC Data Entry User - Once an incident is created , It displayed as 'Verified'

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#495]
**Describe the bug**
Once an incident is created , It displayed as 'Verified'

**To Reproduce**
1. Login as an EC data-entry user 
2. Create an incident 
3. Now click on that and view the incident 
4. check the status of right upper corner

**Expected behavior**
Once an incident is created, which is not a verified one unless it is verified by EC coordinator or some one in higher rank

**Actual Output**
Once an incident is created , It displayed as 'Verified'

**Screenshots**
![verified](https://user-images.githubusercontent.com/56617308/77379479-cb391e80-6d9e-11ea-84ba-090380f64b43.png)

**Comment by MrClemRkz** [comment]
this is completed.
