### ISSUE TITLE
CSV Export - Garbage characters displayed for 'Sinhala' , 'Tamil' Contents

### ISSUE THREAD

**Issue by madhushanig** [ECLK/IncidentManagement#496]
**Describe the bug**
 Garbage characters displayed for 'Sinhala' , 'Tamil' Contents

**To Reproduce**
1. login as any user 
2. export any CVS report with Sinhalese and Tamil content
3. Now check whether Sinhalese and Tamil content available 

**Expected behavior**
Should display Sinhalese and Tamil Unicode properly 

**Actual Output**
Garbage characters displayed for 'Sinhala' , 'Tamil' Contents

**Screenshots**

**Comment by MrClemRkz** [comment]
this is fixed even without the pdf service. at the moment this pdf genertor is on the same backend side on review page.
