### ISSUE TITLE
CRUD on Incident category

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#50]
## User Story
AS AN EC Admin, I WANT to add / edit / delete Incident category SO THAT it can be used when adding new Incidents to the system.

**Comment by MrClemRkz** [comment]
## task breakdown
- [ ] create
- [ ] update
- [ ] delete
- [ ] full category list view

**Comment by ManZzup** [comment]
Djangoadmin provides this feature
do we create a separate admin for this later?

**Comment by MrClemRkz** [comment]
> Djangoadmin provides this feature
> do we create a separate admin for this later?

Django support for this is enough.
