### ISSUE TITLE
'Has Proof' set to 'No' in workflow comments for incident even if proof box is ticked when verifying

### ISSUE THREAD

**Issue by ramdesh** [ECLK/IncidentManagement#518]
**Describe the bug**
The `Has Proof?` value is set to `No` in workflow view for an incident, even if the `verified with proof` checkbox is ticked when verifying.

**To Reproduce**
1. Go to `CREATE`
2. Create a new incident.
3. Go to `REVIEW` and click on the incident just created.
4. Click `VERIFY` and click the `verified with proof` checkbox and verify the incident.
5. The workflow view below the incident shows `Has Proof? No`.

**Expected behavior**
The workflow view below the incident should show `Has Proof? Yes`

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome
 - Version: 83

**Comment by ramdesh** [comment]
@MrClemRkz can you verify that this is a valid issue?

**Comment by MrClemRkz** [comment]
@ramdesh yeah issue exists. we need it to be fixed. yet it's a low priority one.
