### ISSUE TITLE
'serverity' dropdown updated - advanced search

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#523]
- [x] should list only ['high', 'medium', 'low'], while clustering the numbers into them (frontend)
- [x] backend change to filter accordingly

**Comment by ramdesh** [comment]
@MrClemRkz could you please specify which numbers from 1 to 10 constitute `high`, `medium` and `low`? 
I'm assuming the following:
* 1 - 3 (inclusive) : low
* 4 - 6 (inclusive) : medium
* 7 - 10 (inclusive) : high

**Comment by MrClemRkz** [comment]
@ramdesh values updated

**Comment by MrClemRkz** [comment]
completed.
