### ISSUE TITLE
Incident Info/ populate data from service to category.

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#65]

**Comment by lahiru94** [comment]
@MrClemRkz can we close this? Currently, the categories are fetched from a backend endpoint due to the unavailability of a common service.

**Comment by ManZzup** [comment]
@MrClemRkz are we still going to request data externally or keeping them internally?

**Comment by MrClemRkz** [comment]
> @MrClemRkz are we still going to request data externally or keeping them internally?

Let's keep them internally until we are ready to launch the external service.

**Comment by MrClemRkz** [comment]
categories are going to be only in Incident system.
