### ISSUE TITLE
Incident Info: Fix overlapping text labels/ bug

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#68]

**Comment by MrClemRkz** [comment]
With the idea of having consistent look and feel, shall we have the labels shrunk to top always? We can avoid the overlapping with this as well. 

At the same time, if we go by that decision we have to make sure it is the same with the labels which don't animate (eg:- dropdowns, radiobuttons).

**Comment by MrClemRkz** [comment]
## task breakdown 
- [ ] full task

**Comment by ManZzup** [comment]
Is this resolved @MrClemRkz ?

**Comment by MrClemRkz** [comment]
> Is this resolved @MrClemRkz ?

yes. let's close this.
