### ISSUE TITLE
Location Info: Cordinates can be automatically captured by given location pin point on map.

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#71]
upon user trigger event, from a popup or from a new tab/window, should show the map to select a place, there by we collect the coordinates and other information given from map to populate the form.

**Comment by ManZzup** [comment]
@MrClemRkz need clarification on this.

**Comment by MrClemRkz** [comment]
> @MrClemRkz need clarification on this.

description updated.

**Comment by ManZzup** [comment]
@aijdissanayake merge this with #112

**Comment by ManZzup** [comment]
merge with #38
