### ISSUE TITLE
SINGLE INCIDENT VIEW: Include button to quickly add comments, change status, assign staff, or edit information.

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#83]
> On Comment/ Event trail

**Comment by lahiru94** [comment]
Status of an incident is automatically changed when an action is taken. Status after the action will be determined by the type of the action.

**Comment by lahiru94** [comment]
User roles of "complaint manager" and above can change the current assignee from the side-panel in the review incident view.

**Comment by lahiru94** [comment]
The edit button is available in the side pane.

**Comment by lahiru94** [comment]
@ManZzup Assignee backend logic

**Comment by ManZzup** [comment]
Done by 09d3fc9d28c0e3c7f60ea3ee3e726e4ae8943bd4
