### ISSUE TITLE
SINGLE INCIDENT VIEW: Summary and Info bar on right.

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#88]
Show info as, Ref ID, Logged Date and Time, Time from last action, Status, Severity, Set response time, Assignee list.

**Comment by lahiru94** [comment]
- [ ] Generate Ref Ids from backend.
- [ ] Set response time - Make "Required response time"  a dropdown with hourly response time options.
- [ ] Load Suggestions for assignee from backend.

**Comment by lahiru94** [comment]
"Logged Date and Time" available in the Basic INformation tab.

**Comment by lahiru94** [comment]
@lahiru94 Add Following response time details to the side-pane in review Incident view.

- [ ] remaining time duration.
- [ ] deadline.

**Comment by ManZzup** [comment]
Done
