### ISSUE TITLE
SINGLE INCIDENT VIEW: Close with or without comment on popup dialog.

### ISSUE THREAD

**Issue by MrClemRkz** [ECLK/IncidentManagement#98]
workflow:
close button clicked > backend call > modal view for close eligibility/ links to add missing requirements > confirm.
(can submit without a comment as well.)

Closing and incident is available under following scenarios:
- there should be one or more 'out come' comments before closing an incident.
- closing should always take place under the supervision of complain manager or chief complain manager.

**Comment by lahiru94** [comment]
Need to finalize the workflow.

**Comment by MrClemRkz** [comment]
> Need to finalize the workflow.

description updated.

**Comment by ManZzup** [comment]
@ManZzup backend endpoint neeed for outcome checking of incident

**Comment by ManZzup** [comment]
Backend endpoint available at `/incident/<incident_id>/workflow/close`

**Comment by ManZzup** [comment]
Merged to #117
